name: for_dev
description: A project of Rodrigo Manguinho's course about advanced Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  build_runner: ^2.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.4
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/
